version: '2'
services:

  seankilgarriff.com:
      image: zzrot/alpine-caddy
      volumes:
        - ./seankilgarriff.com/public:/var/www/html
      networks:
        - frontend

  calc.seankilgarriff.com:
      image: zzrot/alpine-node
      volumes:
        - ./calc.seankilgarriff.com:/usr/src/app
      working_dir: /usr/src/app
      command: node index.js
      networks:
          - frontend


networks:
      frontend:
